version: '2'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    working_dir: /code/bookShelf
    command: ./docker_entry_point.sh
    volumes:
      - citadel_media:/code/media
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changemeinprod
    depends_on:
      - db

volumes:
  postgres_data:
  citadel_media:
