version: "3.4"

services:
  db:
    image: "${REGISTRY_NAME}postgres:10.1-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - "internal"
    env_file:
      - ./.env
    restart: always
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /code/bookShelf
    image: "${REGISTRY_NAME}devclubiitd/bookshelf:0.1"
    command: ./docker_entry_point.sh
    volumes:
      - citadel_media:/code/media
      - protected_media:/code/protected
      - static_volume:/code/staticfiles
    ports:
      - 6000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    networks:
      - "reverseproxy"
      - "internal"
    env_file:
      - ./.env
    environment:
      - PORT=6000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    links:
      - db:db

  nginx:
    image: "${REGISTRY_NAME}devclubiitd/citadel-nginx:0.1"
    build: ./nginx
    volumes:
      - citadel_media:/code/media
      - protected_media:/code/protected
      - static_volume:/code/staticfiles
    ports:
      - 7000:80
    depends_on:
        - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - "reverseproxy"
      - "internal"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - POSTGRES_HOST_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    restart: always

volumes:
  postgres_data:
  citadel_media:
  static_volume:
  protected_media:

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
